# Generated by Django 4.2.1 on 2023-07-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selected_size',
        ),
        migrations.AddField(
            model_name='product',
            name='selected_km',
            field=models.CharField(default='0-10 000km', max_length=10),
        ),
    ]
