# Generated by Django 4.2.1 on 2023-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_selected_size_product_selected_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selected_km',
            field=models.CharField(default='0-10,000 km', max_length=20),
        ),
    ]
