# Generated by Django 4.2.1 on 2023-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='km',
            field=models.CharField(default='0-10,000 km', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='km',
            field=models.CharField(default='0-10,000 km', max_length=20),
        ),
    ]
