# Generated by Django 4.2.1 on 2023-07-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='value',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Web', 'Web'), ('Member', 'Member')], max_length=50, unique=True),
        ),
    ]
